from typing import overload

Numeric = int | float

@overload
def init(*params: str, plots: int = 1) -> None: ...
@overload
def init(*params: str, plots: list[tuple[int, int, int, int]]) -> None: ...
def msg(message: str, /, append: bool = False) -> None: ...
@overload
def plot(data_set: int, *data: Numeric) -> None: ...
@overload
def plot(data_set: int, *data: list[Numeric]) -> None: ...
