[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "orbital"
version = "v0.0.0"
dynamic = [
    "dependencies"
]

[tool.setuptools.dynamic.dependencies]
file = "requirements.txt"
